% LTNghia

clc;

disp('------> This is a script to calculate keystream bits generated by A5/1 Cipher <------')

% X = 1010101010101010101
X = input('\nEnter values of register X: ','s');
X = X - '0';

% Y = 1100110011001100110011
Y = input('Enter values of register Y: ','s');
Y = Y - '0';

% Z = 11100001111000011110000
Z = input('Enter values of register Z: ','s');
Z = Z - '0';

A51Cipher(X,Y,Z)